- rudder-sdk-core/build.gradle
- rudder-sdk-core/maven.gradle
- rudder-sdk-core/src/main/java/com/rudderlabs/android/sdk/core/RudderClient.java
- rudder-sdk-core/src/main/java/com/rudderlabs/android/sdk/core/RudderMessageBuilder.java
- rudder-sdk-core/src/main/java/com/rudderlabs/android/sdk/core/RudderProperty.java
- rudder-sdk-core/src/main/java/com/rudderlabs/android/sdk/core/RudderServerConfigSource.java
- rudder-sdk-core/src/main/java/com/rudderlabs/android/sdk/core/RudderTraits.java
- rudder-sdk-sample-kotlin/src/main/java/com/rudderlabs/android/sample/kotlin/MainApplication.kt
- rudder-sdk-sample-segment-java/src/main/java/com/rudderlabs/android/sample/segment/java/MainActivity.java
- rudder-sdk-sample-segment-java/src/main/java/com/rudderlabs/android/sample/segment/java/MainApplication.java
- rudder-sdk-sample-segment-java/src/main/res/values/strings.xml
code duplication removed
publishing script separated
updated sample project
> server config response structure fix

- core/src/main/java/com/rudderstack/android/sdk/core/RudderTraits.java
- sample-kotlin-integration/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/27)
> Fix for RudderTraits static getter supports

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/28)
> Event and batch size enforcement

- build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
- sample-kotlin-integration/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
- sample-kotlin/build.gradle
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/29)
> Disable SDK for disabled sources from the dashboard

- README.md
- build.gradle
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- dummy-impl/src/main/java/com/rudderstack/android/integration/dummy/DummyGAIntegration.java
- dummy-impl/src/main/java/com/rudderstack/android/integration/dummy/DummyGAIntegrationImpl.java
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/31)
> Changed eventReplayMessage type to synchronizedList

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/34)
> Add section for onIntegrationReady callbacks

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/35)
> Support for handling corrupt DB

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/38)
> Expose functions to get Advertising ID

- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/42)
> Add public getter(no arg) for RudderClient

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/43)
> Handled case sensitive device.type

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderIntegration.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessageBuilder.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderOption.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderTraits.java
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/44)
> Added externalId logic

- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/45)
> Fixed externalId implementation for reset call

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderOption.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderTraits.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderTraitsBuilder.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/46)
> Fixes for device-mode event replay queue

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-cdn/build.gradle
- sample-cdn/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-cdn/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/49)
> Added API for passing advertisingId

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerConfigManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/48)
> Fetch config from backend on each App open

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- sample-cdn/build.gradle
> Added Getter Method for GroupId in RudderMessage Class 
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/51)
> Added Getter Method for Group ID

- README.md
- build.gradle
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderTraits.java
- sample-cdn/build.gradle
- sample-cdn/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/53)
> Support for setAnonymousId externally

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/54)
> Fixed Screen Bug

- core/src/main/java/com/rudderstack/android/sdk/core/RudderTraits.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/62)
> Fixed Wrong Constant Value for AnonId and UserId in RudderTraits

- README.md
- build.gradle
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-cdn/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/65)
> AdvertisingId update support

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/67)
> Bumped version to 1.0.12

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderOption.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/RudderContextSerializer.java
- sample-cdn/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
…RudderOption object
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/68)
> Provided Support for supplying Custom Context at Event Level through RudderOption object

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/69)
> Fixed how Traits behave on Identify calls

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/70)
> Fixed logs printed in the case of Errors from dataplane

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/73)
> Fixed SqliteDb Crashes for Insert Operations & Strict Mode Errors for SqliteDb operations

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/74)
> Added Initial changes for GDPR Support Android SDK

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/75)
> Bumped version to 1.0.16

- README.md
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/76)
> Changed version to 1.0.15 in Readme

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
> Revert back from gdpr

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
…fore passing to factories
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/79)
> Fixed Missing Properties issue

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/80)
> Android GDPR implementation

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerConfig.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerConfigManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerConfigSource.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerDestination.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerDestinationDefinition.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/81)
> Fixed GSON NPE

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/82)
> Gdpr implementation for 'updateWithAdvertisingId()'

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
- sample-kotlin/build.gradle
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/86)
> Added Support for Setting AnonymousId after SDK Initialization too

- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderOption.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/88)
> Fixed ExternalIds issue

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-kotlin/build.gradle
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/90)
> Added Support for Api Level 19

- README.md
- core/build.gradle
- core/maven.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/94)
> Added old APIs as deprecated for setting anonymousId and deviceToken

- README.md
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderEventFilteringPlugin.java
- core/src/test/java/com/rudderstack/android/sdk/core/RudderEventFilteringPluginTest.java
- Implemented eventFiltering
- Notion link: [here](https://www.notion.so/rudderstacks/d5d15ce4be354e3caae11d4ea9f41477?v=8081ceba15644c85ad7a2cfb918a9c51&p=f1b953672ec84b3f922fe4effbe58e51)
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/104)
> Implemented eventFiltering

- README.md
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderEventFilteringPlugin.java
- core/src/test/java/com/rudderstack/android/sdk/core/RudderEventFilteringPluginTest.java
- Implemented eventFiltering in Android
- Notion ticket [link](https://www.notion.so/rudderstacks/d5d15ce4be354e3caae11d4ea9f41477?v=8081ceba15644c85ad7a2cfb918a9c51&p=f1b953672ec84b3f922fe4effbe58e51)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/106)
> [Release] Version 1.3.0

- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/FlushEventsWorker.java
- core/src/main/java/com/rudderstack/android/sdk/core/FlushUtils.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
- core/src/test/java/android/text/TextUtils.java
- core/src/test/java/com/rudderstack/android/sdk/core/EventRepositoryTest.java
- core/src/test/java/com/rudderstack/android/sdk/core/MockSample.java
- core/src/test/java/com/rudderstack/android/sdk/core/RudderClientTest.java
- core/src/test/java/com/rudderstack/android/sdk/core/RudderLogger.java
- core/src/test/java/com/rudderstack/android/sdk/core/SerializationTest.java
- core/src/test/resources/org/powermock/extensions/configuration.properties
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/111)
> implement flush with single thread executor

- README.md
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/115)
> release changed to 1.4.2

- README.md
- core-mpx/build.gradle
- core-mpx/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core-mpx/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/118)
> Bumped Version to 1.1.0

- core-mpx/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
- dummy-impl/build.gradle
- sample-cdn/build.gradle
- sample-js-integration/RudderAndroidJS/app/build.gradle
- sample-js-integration/RudderAndroidJS/build.gradle
- sample-kotlin-integration/build.gradle
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/FirstActivity.kt
Removed references to Jcenter and Bintray
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/119)
> Removed references to Jcenter and Bintray

- README.md
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/120)
> Made Automatic collection of AdvertisingId configurable by the user

- README.md
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/FlushEventsWorker.java
- core/src/main/java/com/rudderstack/android/sdk/core/FlushUtils.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/MessageUploadLock.java
- core/src/test/java/com/rudderstack/android/sdk/core/EventRepositoryTest.java
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/122)
> Added back synchronization for the message upload in flush api

- core/src/main/java/com/rudderstack/android/sdk/core/ApplicationLifeCycleManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeTransformationManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderFlushWorkManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderNetworkManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/TransformationResponse.java
> Optimised the LifeCycle code by adding a class which will store all the app version.
> (Will work on this) Added TODO's like remove extra line.
> Added comments.
> Will work more on optimising the code and accordingly update the description
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/136)
> Optimised DMT code

- core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeManager.java
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/137)
> Remove log message and optimised device mode manager class.

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeTransformationManager.java
> Removed TODO's and improved log message in Device mode manager class.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/138)
> Improved log messages in Device mode manager class

- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
> Changed manual session data type to long.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/145)
> Fixed manual session data type

- CHANGELOG.md
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderUserSession.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
- sample-kotlin/src/main/AndroidManifest.xml
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/UserSessionActivity.kt
- sample-kotlin/src/main/res/layout/activity_main.xml
- sample-kotlin/src/main/res/layout/activity_user_session.xml
> Session tracking added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/144)
> [Release] Version 1.7.0

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/140)
> Fixed issues in DB Migration

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDataResidencyManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDataResidencyUrls.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerConfigSource.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
- core/src/test/java/com/rudderstack/android/sdk/core/EventRepositoryTest.java
- core/src/test/java/com/rudderstack/android/sdk/core/RudderDataResidencyManagerTest.java
> Address the change in the dataPlaneUrl format.
> Improved test cases.
> Rebased to develop (to include the EventRepositoryTest class changes).
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/154)
> fix: Address the change in the dataPlaneUrl format

- .github/workflows/build.yml
- .github/workflows/draft_new_release.yml
- .github/workflows/release.yml
- .github/workflows/slack-notify.yml
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/160)
> fix: fix draft new release

- build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- sample-kotlin/build.gradle
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> fix: Handled DB Downgrade issue by removing the extra status column
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/158)
> fix: handled db downgrade issue by removing the extra status column

- .github/workflows/draft_new_release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/161)
> fix: remove node

- CHANGELOG.md
- README.md
- build.gradle
- core/build.gradle
- gradle.properties
- scripts/publish-module.gradle
> chore: bumped the version to 1.7.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/165)
> chore: bumped the version to 1.7.1

- build.gradle
- core/build.gradle
fix: fixed issues in release scripts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/166)
> fix: fixed issues in release scripts

- CHANGELOG.md
- README.md
- build.gradle
- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
- sample-kotlin/build.gradle
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainActivity.kt
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> fix: handled the downgrade by deleting the status column in events table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/173)
> [Release] Version 1.7.1

- core/src/main/java/com/rudderstack/android/sdk/core/RudderMessage.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/175)
> feat: removed timestamp from messageId

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- gradle/promote.gradle
**Fixes** 
* rebase on master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/192)
> chore: rebase on master

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderFlushWorkManager.java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/185)
> fix: changed try to try with resources

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderLogger.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
- core/src/test/java/com/rudderstack/android/sdk/core/DBPersistentManagerTest.java
- core/src/test/java/com/rudderstack/android/sdk/core/RudderClientTest.java
> refactor: minor refactoring in the queueing mechanism of messages recieved before saving them to db
> refactor: minor refactoring in the queueing mechanism of messages recieved before saving them to db

- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/consent/ConsentFilterHandler.java
- core/src/main/java/com/rudderstack/android/sdk/core/consent/RudderConsentFilter.java
- core/src/main/java/com/rudderstack/android/sdk/core/consent/RudderConsentFilterWithCloudIntegration.java
- core/src/test/java/com/rudderstack/android/sdk/core/ReflectionUtils.java
- core/src/test/java/com/rudderstack/android/sdk/core/consent/ConsentFilterHandlerTest.java
Added denied consent ids to events
> feat: adding consented values for cloud mode

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
> chore: minor refactor

- core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
- core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
Reverts rudderlabs/rudder-sdk-android#231
> Revert "feat: added support for eliminating device_id from event"

- .github/workflows/adhoc_release-v2.yaml
- .github/workflows/build-v2.yml
- .github/workflows/check_pr_title-v2.yml
- .github/workflows/create_hotfix_branch-v2.yml
- .github/workflows/draft_new_release-v2.yml
- .github/workflows/publish-new-github-release-v2.yml
- .github/workflows/release-v2.yml
- .github/workflows/snapshot_release-v2.yml
> cicd: cicd-v2 Changelist

- .github/workflows/adhoc_release-v2.yaml
- .github/workflows/build-v2.yml
- .github/workflows/check_pr_title-v2.yml
- .github/workflows/create_hotfix_branch-v2.yml
- .github/workflows/draft_new_release-v2.yml
- .github/workflows/publish-new-github-release-v2.yml
- .github/workflows/release-v2.yml
- .github/workflows/snapshot_release-v2.yml
> chore: pulling main into develop

- .github/workflows/build-v2.yml
- .github/workflows/release-v2.yml
- .github/workflows/snapshot_release-v2.yml
> ci: update conditions

- package.json
> ci: fix nx command

- .github/workflows/draft_new_release-v2.yml
> ci: fix token command

- .github/workflows/snapshot_release-v2.yml
> ci: fix snapshot-v2

- .github/workflows/build-v2.yml
- .github/workflows/release-v2.yml
- .github/workflows/snapshot_release-v2.yml
> chore: pulling main into develop 

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistence.java
- core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistenceProvider.java
- core/src/main/java/com/rudderstack/android/sdk/core/persistence/EncryptedPersistence.java
- core/src/main/java/com/rudderstack/android/sdk/core/persistence/Persistence.java
- core/src/main/java/com/rudderstack/android/sdk/core/persistence/PersistenceProvider.java
- sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt
> fix: sdk 392 sqlcipher recreate database if key is wrong

- .github/workflows/build-v2.yml
- .github/workflows/publish-new-github-release-v2.yml
- .github/workflows/release-v2.yml
- .gitignore
- build.gradle
- gradle/artifacts-aar.gradle
- gradle/mvn-publish.gradle
- gradle/promote.gradle
- gsonrudderadapter/project.json
- jacksonrudderadapter/project.json
- jacksonrudderadapter/src/test/java/com/rudderstack/jacksonrudderadapter/ExampleUnitTest.kt
- jacksonrudderadapter/src/test/java/com/rudderstack/jacksonrudderadapter/ParsingTest.kt
- moshirudderadapter/project.json
- repository/project.json
- rudderjsonadapter/project.json
- rudderjsonadapter/src/test/java/com/rudderstack/rudderjsonadapter/ExampleUnitTest.kt
- rudderreporter/build.gradle
- rudderreporter/project.json
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/LibraryMetadata.kt
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/error/Breadcrumb.java
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/error/ErrorClientDelegate.java
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/error/StrictModeHandler.java
- rudderreporter/src/test/java/com/rudderstack/android/ruddermetricsreporterandroid/LibraryMetadataTest.kt
- rudderreporter/src/test/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/DefaultUploaderTest.kt
- web/project.json
- web/src/main/java/com/rudderstack/web/internal/WebServiceImpl.kt
> fix: manual release + last minute fixes

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/ReportManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderServerConfigManager.java
SDK metrics will not be initialized if prior consent from source config is not received.
> fix: sdk 197 metrics initialization fix

- repository/src/main/java/com/rudderstack/android/repository/RudderDatabase.kt
- repository/src/test/java/com/rudderstack/android/repository/RudderDatabaseTest.kt
> fix: fix concurrent modification with concurrent hash map (#218)

- core/build.gradle
- core/src/androidTest/java/com/rudderstack/android/sdk/core/RudderClientInstrumentationTest.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
> feat: add getAnonymousId() API support

- core/src/main/java/com/rudderstack/android/sdk/core/ReportManager.java
issue 620 - null pointer exception in version 1.19.0
> fix: null pointer exception in metrics

- README.md
> added new proguard rule to retain the serialized name annotation
> chore: added new proguard rule to retain the serialized name annotation

- rudderreporter/build.gradle
- rudderreporter/proguard-rules.pro
> expose proguard rules as part of the v2 android reporter library to ensure safer builds
> fix: expose proguard rules as part of the v2 android reporter library to ensure safer builds

- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/Configuration.kt
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/DefaultRudderReporter.kt
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/error/CrashFilter.kt
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/error/DefaultErrorClient.java
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/error/ErrorClient.java
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/error/ImmutableConfig.kt
- rudderreporter/src/test/java/com/rudderstack/android/ruddermetricsreporterandroid/error/CrashFilterTest.kt
- rudderreporter/src/test/java/com/rudderstack/android/ruddermetricsreporterandroid/error/ErrorEventTest.kt
- rudderreporter/src/test/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/error/ImmutableConfigTest.kt
> feat: add crash filter support rudder reporter

- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
- core/src/main/java/com/rudderstack/android/sdk/core/FlushEventsWorker.java
- core/src/main/java/com/rudderstack/android/sdk/core/ReportManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeTransformationManager.java
- core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistenceProvider.java
> feat: adding metrics for workmanager dbEncryption and dmt

- core/src/main/java/com/rudderstack/android/sdk/core/ReportManager.java
> chore: change dmt success tag

- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/LibraryMetadata.kt
- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/error/ErrorModel.kt
- rudderreporter/src/test/java/com/rudderstack/android/ruddermetricsreporterandroid/LibraryMetadataTest.kt
added version to labels in metrics
> feat: added os version to labels

- repository/src/main/java/com/rudderstack/android/repository/RudderDatabase.kt
added discard policy for threads
> fix: added discard policy

- rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/LibraryMetadata.kt
add jvmOverloads in metadata constructor
> fix: added jvm overloads

- core/build.gradle
dependency version update
Version upgrade of rudder reporter so os version is captured.
> chore: update rudder-reporter version

- android/src/main/java/com/rudderstack/android/RudderAnalytics.kt
- android/src/main/java/com/rudderstack/android/internal/infrastructure/ResetImplementationPlugin.kt
- android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
- android/src/test/java/com/rudderstack/android/internal/infrastructure/ResetImplementationPluginTest.kt
- core/src/main/java/com/rudderstack/core/InfrastructurePlugin.kt
- core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
- core/src/test/java/com/rudderstack/core/AnalyticsTest.kt
adds implementation for reset api
> feat: reset api implementation and test

- android/src/test/java/com/rudderstack/android/android/internal/plugins/AndroidContextPluginTest.kt
> chore: add test cases for Android context plugin

- models/src/main/java/com/rudderstack/models/Message.kt
> fix: remove timestamp from message ids

- android/src/main/java/com/rudderstack/android/LifecycleListenerPlugin.kt
- android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt
- android/src/main/java/com/rudderstack/android/internal/plugins/AndroidContextPlugin.kt
> fix: fix display info issue with application context.

- core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
> This PR attempts to fix/synchronise the DBMigration steps. It ensures that DB Migration should be the first to execute before other DB operations can take place.
> fix: race condition fix using semaphore

- android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
- android/src/main/java/com/rudderstack/android/RudderAnalytics.kt
- android/src/main/java/com/rudderstack/android/compat/ConfigurationAndroidBuilder.java
- android/src/main/java/com/rudderstack/android/compat/RudderAnalyticsBuilderCompat.java
- android/src/main/java/com/rudderstack/android/internal/RudderPreferenceManager.kt
- android/src/main/java/com/rudderstack/android/internal/extensions/UserSessionExtensions.kt
- android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt
- android/src/main/java/com/rudderstack/android/internal/plugins/SessionPlugin.kt
- android/src/main/java/com/rudderstack/android/internal/states/UserSessionState.kt
- android/src/main/java/com/rudderstack/android/storage/AndroidStorage.kt
- android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
- android/src/main/java/com/rudderstack/android/utilities/SessionUtils.kt
- android/src/test/java/com/rudderstack/android/android/AndroidStorageTest.kt
- android/src/test/java/com/rudderstack/android/internal/extensions/UserSessionExtensionsTest.kt
- android/src/test/java/com/rudderstack/android/internal/plugins/SessionPluginTest.kt
- android/src/test/java/com/rudderstack/android/utilities/SessionUtilsTest.kt
- core/src/main/java/com/rudderstack/core/Analytics.kt
- core/src/main/java/com/rudderstack/core/State.kt
- core/src/main/java/com/rudderstack/core/compat/AnalyticsBuilderCompat.java
- core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
- core/src/main/java/com/rudderstack/core/internal/FlushScheduler.kt
- models/src/main/java/com/rudderstack/models/android/UserSession.kt
> feat: added session implementation

- android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt
- android/src/main/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPlugin.kt
- android/src/test/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPluginTest.kt
- samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainViewModel.kt
- Feature: Make a flush call each time when the app moves to the background. Also, added test cases for this feature.
- Fixed the flush call instrumentation in the sample app.
> feat: flush events on sent to background

- android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
- android/src/main/java/com/rudderstack/android/internal/RudderPreferenceManager.kt
- android/src/main/java/com/rudderstack/android/internal/plugins/ReinstatePlugin.kt
- android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
- android/src/test/java/com/rudderstack/android/android/AndroidStorageTest.kt
- core/build.gradle
- core/src/main/java/com/rudderstack/core/Configuration.kt
- core/src/main/java/com/rudderstack/core/compat/ConfigurationBuilder.java
- core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
- core/src/main/java/com/rudderstack/core/internal/plugins/GDPRPlugin.kt
- core/src/test/java/com/rudderstack/core/compat/ConfigurationBuilderTest.java
- core/src/test/java/com/rudderstack/core/internal/plugins/EventSizeFilterPluginTest.kt
- core/src/test/java/com/rudderstack/core/internal/plugins/GDPRPluginTest.kt
- Moved optOut API out of the configuration class.
- Refactored the code at various class and also failing unit test cases.
> feat: move optOut out of configuration

- core/build.gradle
- core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
**Fixes**  (https://github.com/rudderlabs/rudder-sdk-android/issues/395)
> fix: serialisation happening on a separate thread executor service

- core/proguard-consumer-rules.pro
- core/src/main/java/com/rudderstack/android/sdk/core/TransformationRequest.java
- sample-kotlin/gradle.properties
- sample-kotlin/proguard-rules.pro
Mentioned the serialized name as annotation.
As a safeguard also added the file to proguard rules
sdk-1774
> fix: key "batch" was being obfuscated due to proguard

- android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
- android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
- android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
- android/src/main/java/com/rudderstack/android/utilities/AnalyticsUtil.kt
- samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
fix: adTrackingEnabled and wifi value for context field in device
> fix: fixed adTrackingEnabled and wifi json value

- core/src/main/java/com/rudderstack/core/internal/DataUploadServiceImpl.kt
- models/src/main/java/com/rudderstack/models/Message.kt
> fix: add sentAt field to each event

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/draft_new_release-v2.yml
- .github/workflows/draft_new_release.yml
- .github/workflows/publish-new-github-release-v2.yml
- .github/workflows/publish-new-github-release.yml
- CODEOWNERS
> chore: update assignees, reviewer and codeowner

- .github/workflows/draft_new_release-v2.yml
- .github/workflows/publish-new-github-release-v2.yml
- CODEOWNERS
> Update code owners and PR reviewer.
> chore: update codeowners and reviewer

- gradle/promote.gradle
- scripts/publish-root.gradle
- Migrate to new Central Repository URLs.
> chore: migrate to maven central urls
