README.md
core/build.gradle
core/maven.gradle
core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java

- Implemented **deepLink** tracking mechanism which is called when app starts for the first time.
- Added property **from_background** in **Application Opened** event. 
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/95)

Implemented deepLink tracking and trackLifeCycle enhancement

---

README.md
core/build.gradle
core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java

- Build version was not saving when LifeCycleEvents is set to false.
- When recordScreenView is set to true and trackLifeCycleEvent is set to false then lifeCycleEvents was flowing. Now if this condition occurs then only screen event will be sent.
- [Notion Card](https://www.notion.so/rudderstacks/d5d15ce4be354e3caae11d4ea9f41477?v=8081ceba15644c85ad7a2cfb918a9c51&p=03c96e5431a045419c4755e410a15aa7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/107)

[BugFix] Enhanced LifeCycleEvents in Android

---

CHANGELOG.md
README.md
core/build.gradle
core/src/main/AndroidManifest.xml
core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderNetwork.java
sample-kotlin/src/main/AndroidManifest.xml

> Made Bluetooth permission optional and from now on the Bluetooth status would be reflected in the payload if and only if the Bluetooth permission is added by the end-user of the SDK
> Fix [#127](https://github.com/rudderlabs/rudder-sdk-android/issues/127) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/130)

Made Bluetooth permission optional 

---

CHANGELOG.md
README.md
core/build.gradle
core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
core/src/main/res/values/strings.xml

> Removed app_name from the String resources of the Core SDK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/134)

Removed app_name from the String resources of the Core SDK

---

core/src/test/java/com/rudderstack/android/sdk/core/EventRepositoryTest.java

> (Fix) Fixed issues in UnitTest Cases for fetchAllEventsFromDB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/153)

(Fix) Fixed issues in UnitTest Cases for fetchAllEventsFromDB

---

.github/workflows/draft_new_release.yml
CHANGELOG.md
README.md
gradle.properties

fixed changelog action
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/170)

fix: downgraded manually incremented version

---

core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java

**Fixes**
* Catching the Null Pointer Exception which was thrown while iterating through the message queue. 
* Synchronizing the code blocks which were adding and retrieving messages from message queue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-android/191)

fix: fixed the null pointer exception thrown while iterating through the message queue 

---

core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderNetworkManager.java
sample-kotlin/build.gradle

- Fix sourceConfig fetching issue which is caused because a newline is getting inserted on some devices due to the encoding mechanism we currently use. So we planned to fix that.

fix: sourceConfig issue by changing encoding to Base64.NO_WRAP

---

core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java

**Fixes** #230 
Usage of deviceIds can be now be disabled through `RudderConfig.Builder().withCollectDeviceId(false);`;
DeviceId is now nullable so anonymous ids will be set to a random UUID string instead of basing it off the device id.

feat: added support for eliminating device_id from event

---

core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
core/src/main/java/com/rudderstack/android/sdk/core/FlushUtils.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderNetworkManager.java

* Moved db operations related to migration to an executor which executes them on a background thread
* Closed leaking cursor object returned on checking if a status column exists
* Closed the input and output streams opened when reading the response of HTTP Connection
* Used try with resources wherever possible to close the auto-closeable
* Reduced the length of code in synchronized blocks for better performance
* Stopped bubbling up of exceptions in RudderNetworkManager

fix: moved db operations to background thread/executor and fixed leaking objects

---

core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java

- This update addresses the replayMessageQueue dumping logic. Starting from this version, whenever the app is started or immediately after the Rudder SDK initialization, all the previous events that are pending to be sent to the device mode factories will be retrieved from the database and dumped.
- Additionally, with the first update using this fixed version, any remaining previous events will be marked as `device_mode_processing_done.` This ensures that any past events will not be dumped to device mode factories anymore.

fix: replay message queue dumping logic

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistenceProvider.java
core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistenceProviderFactory.java

Null or empty encryption key is not valid anymore. In case of null or empty key, the database is no longer encrypted.

fix: sdk 400 ensure empty key is not accepted as encryption key for

---

web/src/main/java/com/rudderstack/web/WebService.kt
web/src/main/java/com/rudderstack/web/internal/WebServiceImpl.kt
web/src/main/java/com/rudderstack/web/utils/GzipUtils.kt
web/src/test/java/com/rudderstack/web/WebApiTest.kt

feat: added gzip support to web

---

core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderUserSessionManager.java

- Implement getSessionId() API support
This PR also contains changes from https://github.com/rudderlabs/rudder-sdk-android/pull/300

feat: add getsessionid api support

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderUserSessionManager.java

- Fix the logic to clear the `sessionId`, when it is changed from on to off.
- Make session logic dependent upon the `withNewLifecycleEvents` API, along with old lifecycle and session tracking API's.

fix: sessionId not getting cleared issue

---

README.md
core/build.gradle
core/proguard-consumer-rules.pro

> expose proguard rules as part of the library to ensure safer builds

fix: expose proguard rules as part of the library to ensure safer builds

---

repository/src/main/java/com/rudderstack/android/repository/Dao.kt
repository/src/test/java/com/rudderstack/android/repository/RudderDatabaseTest.kt
repository/src/test/java/com/rudderstack/android/repository/models/SampleEntity.kt
rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/DefaultRudderReporter.kt
rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/DefaultReservoir.kt
rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/DefaultSyncer.kt
rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/DefaultUploadMediator.kt

fix: table not found in database. added locks

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java

getRudderContext was being called without null check

fix: null pointer exception in alias call

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderUserSession.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderUserSessionManager.java

- Refactor variable and method name: `updateLastEventTimeStamp` to `updateLastActiveTimestamp`.
- Fix: Update the last active timestamp value when the RESET call is made. This will prevent the SDK from generating a new sessionId, when the app is relaunched following a force close after a RESET call has been made. (Note: This fix might be temporary and we can decide to change it based on further discussion.)

fix: update lastActiveTimestamp value when reset call is made

---

core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderNetworkManager.java

Due to a race condition occurring when events are triggered from another thread while the SDK is getting initialized, the generated event payloads are missing `anonymousId`, `context`, & `userId`. 
These events were causing the requests made to the `/batch` endpoint of the data plane to fail with an error message: `Request neither has anonymousId nor userId`.
Hence, to fix this issue, we made the `RudderClient` class thread-safe and added the capability to delete invalid events from the DB when we receive `Request neither has anonymousId nor userId` from the data plane.

fix: batches failed to be sent to data plane

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderApp.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderLibraryInfo.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderOSInfo.java

Synchronization issue in RudderContext when identify called from multiple threads concurrently

fix: added synchronization to RudderContext

---

core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
core/src/test/java/com/rudderstack/android/sdk/core/UtilsTest.java

* When a String is serialized again using Gson, it is converted into a format which cannot be de-serialized back by Gson, fixed this by not serializing a String in the places where it is needed.

fix: fixed serialization of strings twice

---

android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
android/src/test/java/com/rudderstack/android/android/AndroidStorageTest.kt
core/src/main/java/com/rudderstack/core/BasicStorageImpl.kt
core/src/main/java/com/rudderstack/core/RudderUtils.kt
core/src/main/java/com/rudderstack/core/Storage.kt
core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
core/src/main/java/com/rudderstack/core/internal/plugins/EventSizeFilterPlugin.kt
core/src/test/java/com/rudderstack/core/AnalyticsTest.kt
core/src/test/java/com/rudderstack/core/internal/plugins/EventSizeFilterPluginTest.kt
libs/test-common/src/main/java/com/vagabond/testcommon/VerificationStorage.kt
repository/src/main/java/com/rudderstack/android/repository/Dao.kt
repository/src/test/java/com/rudderstack/android/repository/RudderDatabaseTest.kt

- Added the feature to ensure individual message size is not greater than 32KB.
- Added the feature to ensure batch size is not greater than 500KB.
- Added new API `deleteMessagesSync` to delete the message from the local DB/storage in a sync way.

feat: assert size of message and batch

---

core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/test/java/com/rudderstack/android/sdk/core/EventRepositoryTest.java

- Add support for the global `customContext` option. This option could now be passed as a part of the SDK initialisation.
- This value will only be persisted in memory and not in SharedPreference.
- This value will be cleared when a RESET call is made.
- This value will be merged with the localOption `customContext` object (i.e., `customContext` option passed at the event level). While merging the local one would be given preference.

feat: add support for global customContext option

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
sample-kotlin/build.gradle

* Added support for persisting `advertisingId`, so the advertisingId would be attached to all the events made on subsequent app launches.
* Added `clearAdvertisingId()` API on RudderClient to clear the persisted advertisingId. This is an instance method and can be called only after SDK initialization. 
* If the `putAdvertisingId()` API is called when the `auto collection of advertisingId` is enabled, the advertisingId passed by the API is considered, and the auto collection of advertisingId is disabled.
* Auto collection of advertising ID is enabled back only when the manually set advertising Id is cleared by calling the `clearAdvertisementId()` API.

feat: added persistence support for advertisingId and api to clear advertisingId

---

android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt

- When the app moves from background to foreground the `Application Opened` event was not fired. This PR attempts to fix that.

fix: Application Opened event not being fired

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainViewModel.kt

Branch will be rebased against `feat/android` when the base branch will be merged.
In this PR, we are updating the Android Gradle plugin to the latest version, and applying a very small fix with an incompatibility that was caused due to this update.
- Updates project build.gradle agp to the 8.2.2.
- Updates `gradle/wrapper/gradle-wrapper.properties` to the 8.2.2
- Adds some properties in `gradle.properties`
- Kotlin Sample application builds as normal!

feat: updates agp to 8.2.2

---

android/src/main/java/com/rudderstack/android/AnalyticsRegistry.kt
android/src/main/java/com/rudderstack/android/RudderAnalytics.kt
android/src/main/java/com/rudderstack/android/compat/RudderAnalyticsBuilderCompat.java
android/src/test/java/com/rudderstack/android/AnalyticsRegistryTest.kt
android/src/test/java/com/rudderstack/android/android/RudderAnalyticsTest.kt
package-lock.json
package.json

- Add support for initialising the SDK multiple times using different writeKeys.
- I also noticed some issues with the `npm ci` command, due to which the unit test action is failing (refer [here](https://github.com/rudderlabs/rudder-sdk-android/pull/227)). So, to fix that, I update the version of one of the npm packages: https://www.npmjs.com/package/@jnxplus/nx-gradle to the latest version `0.40.1-2`.

feat: add support for multiple sdk initialisation

---

.github/workflows/build-v2.yml
android/build.gradle
app/build.gradle
core/build.gradle
core/src/test/java/com/rudderstack/core/CentralPluginChainTest.kt
dependencies.gradle
gsonrudderadapter/build.gradle
jacksonrudderadapter/build.gradle
libs/navigationplugin/build.gradle.kts
libs/test-common/build.gradle.kts
models/build.gradle
models/src/main/java/com/rudderstack/models/android/RudderTraits.java
moshirudderadapter/build.gradle
repository/build.gradle
rudderjsonadapter/build.gradle
rudderreporter/build.gradle
samples/sample-kotlin-android/build.gradle.kts
samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
web/build.gradle

- After upgrading to the Gradle version `8.2.2`, we noticed that unit test cases were failing, as the Gradle has a compatibility issue with an older Java version `11` (which the project was currently dependent upon). This PR bumps the Java version to `17` throughout the project to address that issue.
- Updated the Java version to `17` in GitHub action, as Gradle `8.2.2` is now dependent upon Java version `17`.
- After upgrading to Gradle version `8.2.2`, we observed that the existing test cases, which utilized `Mockito` to mock the `sealed` Message class, began to fail. So, we have resolved the code issue that was causing the unit test to fail in the `CentralPluginChainTest` class and also used the concrete Message class (instead of mocking the sealed Message class).
**Known Issue**: A …

fix: unit test cases

---

core/build.gradle
core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistenceProvider.java
core/src/main/java/com/rudderstack/android/sdk/core/persistence/EncryptedPersistence.java
sample-kotlin/build.gradle

SDK-1495
fix: #413 
SQL Cipher legacy version is deprecated.
This migration requires user to change the sqlcipher dependency

feat: migrate from sqlcipher legacy to latest version

---

core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java

We noticed that when `Intent.EXTRA_REFERRER` is absent in the `extras` while invoking a deep link, the SDK threw a `NullPointerException`.
Implemented a check to verify whether the `referrer` is `null` or not. If it's not `null`, then it is cast to a string.

fix: deep linking crash

---

CONTRIBUTING.md

We are going to use the new CLA (Google Form link) instead of the old Wufoo link to improve organisation and reduce management/collaboration hassles

docs: update cla link

---

android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt

activity to be broadcasted even if recordScreenView or trackLifecycleEvents is false

fix: activity is now broadcasted irrespective of recordScreenView or trackLifecycle

---

android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
android/src/main/java/com/rudderstack/android/storage/AndroidStorage.kt
android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
android/src/main/java/com/rudderstack/android/storage/FileUtils.kt

Made changes to remove v1 `RudderServerConfig` and `RudderFlushConfig` files, after migration.

fix: delete v1 files server config and flush server config

---

android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
android/src/main/java/com/rudderstack/android/internal/plugins/FillDefaultsPlugin.kt
android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
android/src/test/java/com/rudderstack/android/plugins/ExtractStatePluginTest.kt
android/src/test/java/com/rudderstack/android/plugins/FillDefaultsPluginTest.kt
core/src/main/java/com/rudderstack/core/Analytics.kt
core/src/main/java/com/rudderstack/core/Configuration.kt
core/src/main/java/com/rudderstack/core/Controller.kt
core/src/main/java/com/rudderstack/core/Dsl.kt
core/src/main/java/com/rudderstack/core/RudderOption.kt
core/src/main/java/com/rudderstack/core/compat/ConfigurationBuilder.java
core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
core/src/main/java/com/rudderstack/core/internal/plugins/RudderOptionPlugin.kt
core/src/test/java/com/rudderstack/core/AnalyticsTest.kt
core/src/test/java/com/rudderstack/core/compat/ConfigurationBuilderTest.java
core/src/test/java/com/rudderstack/core/internal/plugins/RudderOptionPluginTest.kt
models/src/main/java/com/rudderstack/models/Extensions.kt
models/src/main/java/com/rudderstack/models/Utils.kt
models/src/test/java/com/rudderstack/models/MessageUtilsTest.kt
samples/sample-kotlin-android/build.gradle.kts
samples/sample-kotlin-android/src/main/AndroidManifest.xml
samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainViewModel.kt

Remove external ids from all messages except identify.
Collection of advertising Id is fixed. Previously the default executor for ad id collection was null.

feat: sdk 1954 misc issues remove external ids and collect ad

---

core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/test/java/com/rudderstack/android/sdk/core/DBPersistentManagerTest.java
settings.gradle

In this PR, we attempt to fix the DB crash issue occurring for a few % of users. This happens while the SDK is being initialised. We have removed the queue-related logic to prevent any hidden thread-related issues. Additionally, since we are now calling `saveEvent()` from the executor in the repository class, we no longer need a separate executor for the `DBInsertionHandlerThread` instance creation.

fix: database crash issue

---

android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
android/src/main/java/com/rudderstack/android/compat/ConfigurationAndroidBuilder.java
android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
android/src/main/java/com/rudderstack/android/internal/plugins/FillDefaultsPlugin.kt
android/src/main/java/com/rudderstack/android/utilities/AnalyticsUtil.kt
android/src/test/java/com/rudderstack/android/plugins/FillDefaultsPluginTest.kt

In this PR, we removed `userId` from the `ConfigurationAndroid` class and also made some other optimisation i.e., now we are directly saving the userId in the storage and now we no longer need to call Analytics.setUserId to save this value. Also fixed one failing test case.

fix: remove userId from the configurationAndroid class

---

android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
android/src/main/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPlugin.kt
android/src/test/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPluginTest.kt
android/src/test/java/com/rudderstack/android/storage/MessageEntityTest.kt
android/src/test/java/com/rudderstack/android/storage/MigrateV1ToV2UtilsTest.kt
core/src/main/java/com/rudderstack/core/Dsl.kt
models/src/main/java/com/rudderstack/models/Message.kt

- Set default flag value to `false` for the `Automatic Screen Event`.
- Send default property (i.e., `automatic` to `true`) for the `Automatic Screen Event`. Also, add a unit test case for the `Automatic Screen Event`.
- Allow setting of `eventName` in screen event. This property will be set in the root as follows:
```
"event": "mainview.MainActivity"
```
- Also fixed a few failing test cases related to the screen event.

fix: screen event

---

android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
core/src/main/java/com/rudderstack/core/RudderOption.kt
core/src/test/java/com/rudderstack/core/RudderOptionTest.kt
models/src/main/java/com/rudderstack/models/Extensions.kt
models/src/test/java/com/rudderstack/models/MessageUtilsTest.kt

I observed an issue while setting the `externalId's` in identify event. Suppose when two identify events are made:
```
RudderAnalyticsUtils.analytics.identify(
userId = "user 1",
options = RudderOption().apply {
putExternalId("brazeExternalID", "12345")
putExternalId("amplitudeExternalID", "67890")
putExternalId("adobeExternalID", "67890")
}
)
RudderAnalyticsUtils.analytics.identify(
userId = "user 1",
options = RudderOption().apply {
putExternalId("brazeExternalID", "12345-2")
putExternalId("amplitudeExternalID", "67890-2")
putExternalId("firebaseExternalID", "67890")
}
)
```
Then the expected behaviour (as per v1 SDK) is to merge the externalId of both the identify events giving higher preference to the second identify event externalId. The final payload will look like this:
``` …
```

fix: prevent setting duplicate externalId types

---

core/src/main/java/com/rudderstack/android/sdk/core/Constants.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderConfig.java
core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
sample-kotlin/src/main/java/com/rudderstack/android/sample/kotlin/MainApplication.kt

Added a builder method `withEventDispatchSleepInterval(int eventDispatchSleepInterval)` that allows users to configure the sleep interval for the `CloudModeProcessor` when it is idle (i.e., no events to process). The default interval is `1 second`, ensuring no change in existing behaviour. This feature enables users to conserve battery by putting the `CloudModeProcessor` thread to sleep for a specified interval.
Also, note that the value specified in `withEventDispatchSleepInterval(...)` should not exceed the `sleepTimeOut` value; otherwise, the default value of 1 second will be used.
**NOTE**: Currently, the default behaviour dictates that if there are no events to process, the `CloudModeProcessor` checks every `1 second` for new events in the database. This ensures prompt event …

feat: add a configurable setting to put the CloudModeProcessor to sleep for a specified interval

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/util/ExponentialBackOff.java
core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
core/src/test/java/com/rudderstack/android/sdk/core/ExponentialBackOffTest.java

- This PR removes the existing retry mechanism for network errors and replaces it with an **exponential retry mechanism with jitter**. Now, retries will occur exponentially for every **4xx** and **5xx** status code (except 400 and 404). If the network is unavailable, retries will continue with a one-second delay.
- The maximum limit is 5 minutes; once this limit is reached, the retry process will start over from the beginning.
- Example sequence:
```
5sec, 7sec, 22 sec, 42 sec, 56 sec, 3 min 11 sec, 5 min 0 sec,
3 sec
```
**NOTE**: No event is deleted in this process.

feat: implement exponential retry mechanism for handling network errors

---

.github/workflows/draft_new_release-v2.yml
.github/workflows/publish-new-github-release-v2.yml
.gitignore
gsonrudderadapter/project.json
jacksonrudderadapter/project.json
models/project.json
moshirudderadapter/project.json
package-lock.json
package.json
repository/project.json
rudderjsonadapter/project.json
rudderreporter/project.json
rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/DefaultUploadMediator.kt
web/project.json

- In this PR, we've updated the metrics endpoint from `sdkmetrics` to `rsaMetrics`.
- The PR reviewer has also been updated.
- CI: Updated build and test executors in all modules.
- CI: Exclude all modules from releasing except `repository` and `rudderreporter`. These change has been done for `release` (Changelog generation), `release:github` (Push GitHub releases), `release:sonatype` (Releasing the affected packages to sonatype) and `release-snapshot:sonatype` (Releasing snapshot versions to sonatype).
**NOTE**: Instead of the next minor version `0.5.0`, we need to release these changes in version `0.6.0`, as the v1 SDK depends upon [0.4.0, 0.6.0). So if we release it as `0.5.0`, it might cause an issue. Therefore, I've manually created and pushed …

feat: change the metrics endpoint to `rsaMetrics`

---

core/build.gradle
core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
core/src/main/java/com/rudderstack/android/sdk/core/ReportManager.java

- Add the option to configure `dataPlaneUrl` as the metrics URL and remove the default metric URL.
- Bump and fix the `rudderreporter` to `0.6.0`.
- Fix the `gsonrudderadapter` to `0.2.0`. (There is no change. We just fixed it to a particular version.)

feat: add option to configure `dataPlaneUrl` as the metrics url

---

core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistence.java

- In this PR, we are handling the database crash issue caused on Amazon devices when the app is mostly in the background.
- We are catching `SQLiteCantOpenDatabaseException` when we check if the database is accessible or not and if an exception occurs we return false indicating the database is not accessible.
- If such an exception occurs then all the events will be lost.
- Values like userId, traits, etc., not stored in the database will continue to be stored in shared preferences as usual.

fix: handle db crash issue on Amazon devices

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java

- Added an `Alias` API with `previousId` support. Now, `previousId` can be passed and will be preferred over the existing `userId` or `anonymousId`.
- New Alias API:
```
public void alias(@NonNull String newId, @Nullable RudderOption option, @Nullable String previousId)
```
- This is to bring it in parity with the JS SDK so that `previousId` can be explicitly passed if needed.
NOTE: The change is backwards compatible, as we are introducing a new Alias API which adds a new behaviour to the existing payload schema.
Objective: We need to test, if `previousId` is passed then it should be used, else the existing behaviour should continue i.e., userId or anonymousId should be used.
- Make an `alias` event and explicitly pass `previousId` field -> It should be set as the `previousId`.
- Existing …

feat: add alias api with previousId support

---

core/src/main/java/com/rudderstack/android/sdk/core/FlushUtils.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeManager.java

- We are addressing the invalid JSON issue by filtering out such messages during batch construction and ensuring their removal from the database.
- Our hypothesis is that the invalid message string is somehow a single character, based on the sample invalid message payloads we have observed.
- To resolve this issue, we need to filter the invalid events from the database.
- First, we need to prevent the construction of an invalid batch payload by detecting the invalid JSON:
- **Filtering invalid events during batch construction**: For each message, we check whether it is a single character (based on our hypothesis). If it is, we treat it as invalid JSON and exclude it from the batch. If it is a valid event, we construct a proper batch of events. The goal is to ensure that the batch does not …

fix: handle invalid json issue

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java
core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java

- This PR resolves the fatal error caused by `OutOfMemoryError` in `RudderCloudModeManager`. 
- The error actually occurs in `DBPersistentManager` in `getDBRecordCount` method. This method is called in `maintainDBThreshold` method which is in turn called in a thread in `startCloudModeProcessor`. 
- The error is unrelated to any database operations and occurs at OS level, therefore this PR catches the error and logs a message in `startCloudModeProcessor` in `RudderCloudModeManager`.
- During the catching of the error, a Thread.sleep is added to prevent the while loop from running constantly in case the exception is thrown again.

refactor: catch OutOfMemoryError in RudderCloudModeManager

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java

- Change the `alias` API
from:
```
public void alias(@NonNull String newId, @Nullable RudderOption option, @Nullable String previousId)
```
to
```
public void alias(@NonNull String newId, @Nullable String previousId, @Nullable RudderOption option)
```

chore: correct `alias` api by adding previousId argument in the middle

---

core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java

- We have updated the hard limit on event ingestion size from 32 KB to 64KB. 
- So, now SDK allows to make an event of size less than or equal to 64 KB.
- Previously, we log the following error message with the event size limit of 32 KB:
- Now, we log the following error message with the event size limit of 64 KB:

feat: increase MAX_EVENT_SIZE from 32 KB to 64 KB

---

core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceModeManager.java
sample-kotlin/src/main/AndroidManifest.xml
sample-kotlin/src/main/res/xml/network_security_config.xml

- Added a fix to avoid NPE (NullPointerException) which occurs if custom factory is added and the Android source doesn't have any destination attached to it. Now, we are first checking if eventFilteringPlugin object is null or not before accessing it, which prevents the NPE.
- I also updated the `networkSecurityConfig` in the sample app. This will be helpful to test the localhost URL.
- I've ensured that existing event filtering functionality works as expected.
- I've ensure that custom factory integration works as expected and doesn't throw any exception.

fix: resolve NPE issue in the custom factory feature

---

.github/workflows/release.yml
.github/workflows/snapshot_release.yml

This is to fix the failing test in the release github actions. Refer here: https://github.com/rudderlabs/rudder-sdk-android/actions/runs/13965287907/job/39094393380?pr=502 for the failing action, we need to set the Java to v11. For build it's already set to v11.

ci: set java to v11 in the release actions

---

core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
core/src/main/java/com/rudderstack/android/sdk/core/FlushUtils.java
core/src/main/java/com/rudderstack/android/sdk/core/RudderCloudModeManager.java

- Added the logic to catch the `SQLiteFullException` in the `DBPersistentManager.java` and `FlushUtils.java`.
- Also, added a 1-second sleep in case of an exception in `RudderCloudModeManager.java`.

fix: handle SQLiteFullException in event saving and flushing logic
